# Generated by Django 5.2.3 on 2025-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly')], default='W', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='firstname',
            field=models.CharField(default='andre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
