# Generated by Django 5.2.3 on 2025-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobpost_type_alter_jobpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='INR', max_length=10),
            preserve_default=False,
        ),
    ]
